language: cpp
compiler:
- clang
before_install:
- sudo apt-get update
install:
- sudo apt-get install libvlc-dev libvlccore-dev
- git clone https://github.com/openhome/ohdevtools.git
script: ./go build
