language: cpp
compiler:
- clang
before_install:
- sudo apt-get update
addons:
  apt:
    packages:
    - libvlc-dev
    - libvlccore-dev
install:
- git clone https://github.com/openhome/ohdevtools.git
script: ./go build
